name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - 'v*'
  # Optional: Deploy on push to main branch
  # push:
  #   branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        env:
          # Add your environment variables here
          # Example for Vite:
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}
          # VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          # Example for Create React App:
          # REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
